(add-to-list 'load-path "~/.emacs.d/")

(load-library "utils")
(load-library "align")
(load-library "dired-x")
(load-library "find")
(load-library "buffers")
(load-library "editing")
(load-library "sanitize")
(load-library "styles")
(load-library "tagging")
(load-library "settings")
(load-library "display")
(load-library "bindings")
